service/service.go

- Extension is xlsx not xls
Verify route is correct
Anyone

Change route from XLS to XLSX

---

config/config.go
config/config_test.go
handlers/download.go
main.go
service/service.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/data.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
vendor/vendor.json

Update download service to send authorization header to dataset api
Verify logic correct
Team B

Update download service to send authorization header to dataset api

---

README.md
config/config.go
config/config_test.go

- Add `bearer` in front of service token
Verify logic correct
Anyone

Add bearer in front of auth token

---

config/config.go

Update config package to pre process environment variables

 Update config package to pre process environment variables

---

dp-download-service.nomad

remove nomad service name suffix

remove nomad service name suffix

---

README.md
config/config.go
config/config_test.go
handlers/download.go
handlers/download_test.go
handlers/mocks/mocks.go
main.go
service/service.go
swagger.yml
vendor/github.com/ONSdigital/go-ns/clients/filter/data.go
vendor/github.com/ONSdigital/go-ns/clients/filter/filter.go
vendor/vendor.json

- Update download service to include filter output downloads
- Update swagger spec
- Verify logic is correct
### Who can review
- Anyone

Update download service to include filter output downloads

---

.gitignore
config/config.go
config/config_test.go
handlers/download.go
handlers/download_test.go
policy.hcl

* Update path used to store download keys in vault
* Default to publishing 'mode'
* Added .gitignore
* Remove unused variables

Update path used to store download keys in vault

---

handlers/download.go
main.go
service/service.go

* Add the download service token header to filter API requests
* Improved logging around private downloads

Add the download service token header to filter API requests

---

vendor/github.com/ONSdigital/go-ns/clients/clientlog/clientlog.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/data.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
vendor/github.com/ONSdigital/go-ns/clients/filter/data.go
vendor/github.com/ONSdigital/go-ns/clients/filter/filter.go
vendor/github.com/ONSdigital/go-ns/log/log.go
vendor/vendor.json

govendor updated go-ns packages to support flattened filter events

govendor updated go-ns packages to support flattened filter events

---

handlers/download.go
service/service.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/data.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
vendor/vendor.json

Add route to serve CSVW download
Check code does what it should
Dependent PRs for testing:
https://github.com/ONSdigital/go-ns/pull/121
https://github.com/ONSdigital/dp-dataset-api/pull/162
https://github.com/ONSdigital/dp-dataset-exporter/pull/46
Anyone

Add route for CSVW download

---

dp-download-service.nomad

What
Using docker reduces the likelihood of timeout on deploy
How to review
check for typos
check repo names are consistent
check web/publishing both updated
Who can review
anyone

Update nomad plan to use docker instead of exec driver

---

vendor/github.com/ONSdigital/go-ns/LICENSE.md
vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
vendor/github.com/ONSdigital/go-ns/common/collection.go
vendor/github.com/ONSdigital/go-ns/common/identity.go
vendor/github.com/ONSdigital/go-ns/common/models.go
vendor/github.com/ONSdigital/go-ns/common/rchttp.go
vendor/vendor.json

update datasetAPI client

---

dp-download-service.nomad

updated nomad plan to use /health endpoint instead of /healthcheck
verify that the changes make sense, once this is merged, concourse should be able to deploy to develop correctly.
Anyone.

Update /health endpoint in nomad plan

---

Makefile

Fix audit job on CI by changing `nancy` command. This is needed to release previously approved code.
- Confirm `make audit` works
- Ensure `pr-audit` [concourse job](https://concourse.onsdigital.co.uk/teams/main/pipelines/dp-download-service?group=prs) passes successfully.
Anyone but me

Fix CI audit job

---

Makefile
swagger.yml

Release branch containing…
- Updated swagger spec to contain csv-metadata endpoint
- Add `-json` to audit command syntax
Ensure only expected commit and tests pass
Anyone but me

Release 1.14.0

---

main.go
service/service.go

Refactor main and service.go so that they are more in line with the standard,
And to make testable with the component testing framework
Run the app locally with `make debug` and then `curl http://localhost:23600/health`
Check that response looks sane.
Shutdown app and check that shutdown logs look sane.
Anyone familiar with how the standardised micro-services should work

Refactor service and main

---

main.go
service/service.go

Refactored main to enable decency injection required by dp-component-test framework
Check the health still works
Anyone

Refactor service and main to be more in line with standard and to make testable

---

Dockerfile.local
Makefile

As per title.
Visual inspection.
Anyone

Add '-race' to debug-run, and update base docker image

---

content/s3_stream_writer.go
downloads/downloader.go
go.mod
go.sum
handlers/download_test.go
main.go
service/external/external.go

Update to latest healthcheck library
Visual inspection, run tests.
Anyone

Update healthcheck to v1.2.3 and fix file formatting

---

Makefile
handlers/callback.go
handlers/callback_test.go
main.go
scripts/main.go
service/service.go

Setting up linting for CI

---

api/download.go
config/config.go
features/ons_website_download.feature
features/steps/download_service_component.go
features/steps/steps.go
files/retreiver.go
go.mod
go.sum
handlers/download.go
main_test.go
service/service.go

Download A Single unencrypted chuck

---

api/download.go
api/download_test.go
features/ons_website_download.feature
features/steps/download_service_component.go
features/steps/external.go
features/steps/steps.go
files/retreiver.go
files/retreiver_test.go
go.mod
go.sum
service/service.go

files are decrypted on the fly

Encrypted download file

---

api/download_test.go
features/steps/steps.go
files/retreiver.go
service/service.go
swagger.yml

Remove v1 call to files-api in line with new endpoints
Stuff

Remove v1 replace with download-new

---

Dockerfile
Makefile
api/download.go
api/download_test.go
ci/lint.yml
ci/scripts/lint.sh
features/ons_reviewer_downloads_file.feature
features/ons_website_download.feature
features/steps/steps.go
files/retreiver.go
files/retreiver_test.go

Hex coding

---

README.md
api/download.go
api/download_test.go
api/errors.go
features/ons_website_download.feature
files/metadata.go
files/metadata_test.go

Download refactor

---

features/ons_reviewer_downloads_file.feature
features/ons_website_download.feature
features/steps/steps.go
service/service.go

Handling any characters in a URL

---

swagger.yml

Also split-out host, scheme, and basepath

Updated swagger doc with required and deprecated info

---

api/download_test.go
api/errors.go
features/ons_reviewer_downloads_file.feature
features/ons_website_download.feature
files/retreiver.go
files/retreiver_test.go

Handle filesapi errors

---

README.md

Writing the intro to download service

---

README.md

Updating Copyright

---

api/download.go
api/download_test.go
api/errors.go
features/ons_reviewer_downloads_file.feature
features/ons_website_download.feature
go.mod
go.sum

Cach configuration

---

scripts/fix-download-links.js
service/service.go

previously the route was misconfigured and the js config file did not include xlsx which has now been added

patch: correct xlsx file routes and config

---

handlers/download.go

Adding debugging to test in sandbox to figure out why CMD downloads no longer work with the XLSX change.
Ensure the changes make sense.
Anyone.

Adding further debugging

---

downloads/downloader.go

Further debugging for sandbox.
Ensure the changes make sense.
Anyone.

More debugging

---

downloads/downloader.go

Logging out variant for debugging.
Ensure the changes make sense.
Anyone.

Log out variant

---

service/service.go

Update xls download route for filtered dataset
Changes make sense
Anyone

update xls download route

---

README.md
config/config.go
main.go
service/service.go

Add otel feature flag.
Ensure the changes make sense and the tests pass.
Anyone ONS.

Add otel feature flag

---

downloads/downloader.go
handlers/download.go

Added some log data to determine the issue with downloading xlsx files.
Ensure the changes make sense and the tests pass.
Anyone ONS.

Adding debug statements

---

dp-download-service.nomad

As per title.
Ensure changes are similar to whats in babbage for 'spread'.
Anyone.

Ensure deployments spread over availability zones

---

Dockerfile.concourse

Updating dockerfile.concourse to use Ubuntu-22 as requested by the platform team.
Check updated image name with whats in CI elastic container registry.
Anyone.

Updating dockerfile.concourse to ubuntu-22

---

features/download_files_web_mode.feature

- updated the component test for the `downloads/files/{path}` endpoint in WEB mode
- check if the component tests are passed
anyone

fixed the component test for web mode
